// src/lib/components/utils/SwitchButton.svelte
<script lang="ts">
  export let value: boolean
</script>

<button
  class="switch-button {value ? 'switch-button-active' : ''}"
  type="button"
  on:click="{() => value = !value}"
>
  <div class="switch-button__left-side side-wrapper">
    <slot name="left-side" />
  </div>
  <div class="switch-button__right-side side-wrapper">
    <slot name="right-side" />
  </div>
</button>

<style lang="scss">
  .switch-button {
    --button-height: 1.5rem;
    --button-width: 2.75rem;

    width: var(--button-width);
    height: var(--button-height);
    padding: 2px;
    position: relative;

    border-radius: calc(var(--button-height) / 2);
    background: var(--bg-clr-secondary);

    &:focus {
      box-shadow: var(--focus-shadow-offset);
    }

    &-active::after {
      transform: translateX(calc(var(--button-width) - var(--button-height)));
    }

    &::after {
      height: 100%;
      aspect-ratio: 1;
      content: '';

      display: block;
      border-radius: 50%;
      background: var(--cta-clr-primary);
      transition: transform var(--transition-timing) ease-in-out;
    }

    &__left-side {
      color: var(--bg-clr-primary);
    }

    &-active .switch-button__left-side {
      color: var(--font-clr-primary);
    }

    &__right-side {
      transform: translateX(calc(var(--button-width) - var(--button-height)));
      color: var(--font-clr-primary);
    }

    &-active .switch-button__right-side {
      color: var(--bg-clr-primary);
    }
  }

  :global(.app-wrapper[dark-mode="true"]) .switch-button-active .switch-button__right-side {
    color: var(--font-clr-primary);
  }

  .side-wrapper {
    height: 100%;
    aspect-ratio: 1;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 10;

    display: flex;
    align-items: center;
    justify-content: center;
    transition: color 150ms ease-in-out;
  }

  // @media (min-width: 500px) {
  //   .switch-button {
  //     --button-height: 2rem;
  //     --button-width: 3.75rem;
  //   }
  // }
</style>

// src/components/SwitchButton.vue
<script lang="ts" setup>
import SvgWrapper from './SvgWrapper.vue'

const props = withDefaults(defineProps<{
  isActive: boolean
  icon?: string
}>(), { icon: '' })
</script>

<template>
  <button class="switch-btn-wrapper">
    <div
      class="switch-btn-toggle"
      :class="{ 'switch-btn-toggle--active': props.isActive }"
    >
      <svg-wrapper
        v-if="props.icon"
        :icon="icon"
      />
    </div>
  </button>
</template>

<style lang="scss" scoped>
.switch-btn-wrapper {
  --height: 1.8rem;
  --width: 3rem;

  width: var(--width);
  height: var(--height);
  padding: 0 2px;
  background: var(--secondary-clr);
  border-radius: calc(var(--height) / 2);

  display: flex;
  align-items: center;

  &:focus {
    outline: 0;
    box-shadow: var(--focus-outline);
  }
}

.switch-btn-toggle {
  --size: calc(var(--height) * 0.8);

  width: var(--size);
  height: var(--size);
  padding: .1rem;
  transform: translateX(0);

  background: var(--third-clr);
  border-radius: 50%;
  transition:
    transform var(--t-duration) ease-in-out,
    background var(--t-duration) ease-in-out;
  color: var(--font-secondary-clr);

  &--active {
    background: var(--call-to-action-clr);
    transform: translateX(calc(var(--width) - var(--size) - 4px));
  }
}

[color-mode="light"] .switch-btn-toggle--active {
  color: var(--font-inverse-clr);
}
</style>
